language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t jrowbotham93/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jrowbotham93/react-test npm test

after_success:
  - docker build -t jrowbotham93/multi-client ./client
  - docker build -t jrowbotham93/multi-worker ./worker
  - docker build -t jrowbotham93/multi-server ./server
  - docker build -t jrowbotham93/multi-nginx ./nginx
  # password from travis and pipe into next command as stdin
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push jrowbotham93/multi-client
  - docker push jrowbotham93/multi-worker
  - docker push jrowbotham93/multi-server
  - docker push jrowbotham93/multi-nginx

region: 'eu-west-2'
app: 'multi-docker'
env: 'MultiDocker-env-1'
bucket_name: 'elasticbeanstalk-eu-west-2-951823300441'
bucket_path: 'multi-docker'
access_key_id: $AWS_ACCESS_KEY
secret_access_key: $AWS_SECRET_KEY
