language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t jrowbotham/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jrowbotham/react-test npm test

after_success:
  - docker build -t jrowbotham/multi-client ./client
  - docker build -t jrowbotham/multi-worker ./worker
  - docker build -t jrowbotham/multi-server ./server
  - docker build -t jrowbotham/multi-nginx ./nginx
  # password from travis and pipe into next command as stdin
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push jrowbotham/multi-client
  - docker push jrowbotham/multi-worker
  - docker push jrowbotham/multi-server
  - docker push jrowbotham/multi-nginx
